const test=require('node:test');const assert=require('node:assert/strict');const C=require('../site/core.js');
const v={id:'AbCdEfGhI01',title:'test',views:1000,subscribers:100,fetchedAt:new Date().toISOString()};
test('like then candidate keeps like',()=>{let s=C.apply(C.apply(C.blank(),v,'origin_foreign'),v,'like');s=C.apply(s,v,'candidate');assert.equal(s.records[v.id].rating,'like');assert.equal(s.records[v.id].stage,'candidate');});
test('candidate removal not dislike',()=>{let s=C.apply(C.apply(C.apply(C.blank(),v,'origin_foreign'),v,'like'),v,'candidate');s=C.apply(s,v,'uncandidate');assert.equal(s.records[v.id].rating,'like');assert.equal(s.records[v.id].stage,null);});
test('done from discovery neutral rating',()=>{const s=C.apply(C.blank(),v,'done');assert.equal(s.records[v.id].rating,null);assert.equal(s.records[v.id].stage,'done');});
test('unrate keeps production stage',()=>{let s=C.apply(C.apply(C.apply(C.blank(),v,'origin_foreign'),v,'like'),v,'candidate');s=C.apply(s,v,'unrate');assert.equal(s.records[v.id].rating,null);assert.equal(s.records[v.id].stage,'candidate');});
test('state input remains immutable',()=>{const s=C.blank();C.apply(s,v,'like');assert.equal(Object.keys(s.records).length,0);});
test('ratio unknown and zero',()=>{assert.equal(C.ratio(v),10);assert.equal(C.ratio({...v,subscribers:0}),null);assert.equal(C.ratio({...v,subscribers:null}),null);});
test('backup removes API metadata',()=>{const b=C.exportData(C.apply(C.blank(),v,'like'));assert.equal(b.records[v.id].cache,undefined);assert.equal(b.records[v.id].rating,'like');});
test('expired metadata removed, notes retained',()=>{let s=C.apply(C.blank(),{...v,fetchedAt:'2020-01-01T00:00:00Z'},'like');s.records[v.id].memo='keep';s=C.normalize(s);assert.equal(s.records[v.id].cache,null);assert.equal(s.records[v.id].memo,'keep');});
test('bad schema rejected',()=>assert.throws(()=>C.normalize({schema:9,records:{}})));
test('merge newer wins',()=>{let a=C.apply(C.blank(),v,'like','2026-09-01T00:00:00Z'),b=C.apply(C.blank(),v,'dislike','2026-09-02T00:00:00Z');assert.equal(C.merge(a,b).records[v.id].rating,'dislike');});
test('YouTube links parsed',()=>{assert.equal(C.parseLink('https://youtu.be/AbCdEfGhI01?t=1'),v.id);assert.equal(C.parseLink('https://www.youtube.com/shorts/AbCdEfGhI01'),v.id);assert.equal(C.parseLink('https://www.youtube.com/watch?v=AbCdEfGhI01'),v.id);});
test('unsafe links rejected',()=>{for(const x of ['javascript:alert(1)','https://youtube.com.evil.com/watch?v=AbCdEfGhI01','http://youtu.be/AbCdEfGhI01'])assert.throws(()=>C.parseLink(x));});

test('unknown metadata never determines origin',()=>{assert.equal(C.originOf({}), 'unknown');assert.equal(C.ready({...v,title:'Korean film',country:'US'},{}),false);});
test('unknown cannot enter production candidates',()=>{assert.throws(()=>C.apply(C.blank(),v,'candidate'),/원작/);});
test('legacy record migration preserves rating, stage, memo',()=>{const old={schema:1,records:{[v.id]:{id:v.id,rating:'like',stage:'candidate',memo:'keep me'}}};const r=C.normalize(old).records[v.id];assert.equal(r.rating,'like');assert.equal(r.stage,'candidate');assert.equal(r.memo,'keep me');assert.equal(r.origin,'unknown');});
test('Korean exclusion preserves preference and notes',()=>{let s=C.apply(C.apply(C.apply(C.blank(),v,'origin_foreign'),v,'like'),v,'candidate');s.records[v.id].memo='unchanged';s=C.apply(s,v,'origin_korean');const r=s.records[v.id];assert.equal(r.rating,'like');assert.equal(r.stage,'candidate');assert.equal(r.memo,'unchanged');assert.equal(C.originOf(r),'korean');assert.equal(C.ready(v,r),false);assert.equal(C.needsReview(v,r),false);});
test('origin reset sends item to unknown review',()=>{let s=C.apply(C.blank(),v,'origin_foreign');s=C.apply(s,v,'origin_reset');assert.equal(C.needsReview(v,s.records[v.id]),true);});
test('origin review included in metadata-free backup',()=>{const s=C.apply(C.blank(),v,'origin_korean');const backup=C.exportData(s);assert.equal(backup.records[v.id].origin,'korean');assert.equal(backup.records[v.id].cache,undefined);assert.equal(C.normalize(backup).records[v.id].origin,'korean');});
test('origin decisions for one video do not label other clips',()=>{const s=C.apply(C.blank(),v,'origin_korean');const another={...v,id:'AbCdEfGhI02',title:'same film'};assert.equal(C.originOf(s.records[another.id]),'unknown');});
test('samples can test candidate behavior without a real country decision',()=>{const demo={id:'demo-1'};const s=C.apply(C.apply(C.blank(),demo,'like'),demo,'candidate');assert.equal(s.records[demo.id].stage,'candidate');});
test('disliked and done items do not clog pending review',()=>{assert.equal(C.needsReview(v,{rating:'dislike'}),false);assert.equal(C.needsReview(v,{stage:'done'}),false);assert.equal(C.needsReview(v,{rating:'like'}),true);});

const fvideo={...v,durationSeconds:90,language:'en',screenKind:'film',views:100000,subscribers:5000};
const defaults=()=>C.defaultFilters();
test('default subscribers are 10000',()=>assert.equal(defaults().maxSubscribers,10000));
test('5000 subscriber boundary inclusive',()=>{const f={...defaults(),maxSubscribers:5000};assert(C.matchesFilters(fvideo,{},f));assert(!C.matchesFilters({...fvideo,subscribers:5001},{},f));});
test('10000 subscriber boundary inclusive',()=>{assert(C.matchesFilters({...fvideo,subscribers:10000},{},defaults()));assert(!C.matchesFilters({...fvideo,subscribers:10001},{},defaults()));});
test('unknown subscriber not zero',()=>{for(const sub of [null,undefined,NaN,'4000'])assert(!C.matchesFilters({...fvideo,subscribers:sub},{},defaults()));});
test('unknown subscriber allowed only without cap',()=>assert(C.matchesFilters({...fvideo,subscribers:null},{},{...defaults(),maxSubscribers:0})));
test('zero subscribers valid but no ratio',()=>{assert(C.matchesFilters({...fvideo,subscribers:0},{},defaults()));assert.equal(C.ratio({...fvideo,subscribers:0}),null);});
test('duration range inclusive and editable',()=>{const f={...defaults(),minSeconds:30,maxSeconds:90};for(const d of [30,90])assert(C.matchesFilters({...fvideo,durationSeconds:d},{},f));for(const d of [29,91,null])assert(!C.matchesFilters({...fvideo,durationSeconds:d},{},f));});
test('minimum view boundary',()=>{assert(C.matchesFilters({...fvideo,views:100000},{},defaults()));assert(!C.matchesFilters({...fvideo,views:99999},{},defaults()));});
test('default languages remain multilingual',()=>{assert(C.matchesFilters({...fvideo,language:'es'},{},defaults()));assert(C.matchesFilters({...fvideo,language:'ja'},{},defaults()));});
test('Hindi Arabic not shown by default including scripts',()=>{for(const lang of ['hi','ar','ar-script','indic-script'])assert(!C.matchesFilters({...fvideo,language:lang},{},defaults()));});
test('explicitly enabling languages works',()=>{const f={...defaults(),languages:['ar','hi']};assert(C.matchesFilters({...fvideo,language:'ar'},{},f));assert(C.matchesFilters({...fvideo,language:'hi'},{},f));});
test('unknown language only when requested',()=>{assert(!C.matchesFilters({...fvideo,language:'unknown'},{},defaults()));assert(C.matchesFilters({...fvideo,language:'unknown'},{},{...defaults(),includeUnknownLanguage:true}));});
test('selecting no languages gives zero not all',()=>assert(!C.matchesFilters(fvideo,{},{...defaults(),languages:[]})));
test('default screen clues exclude irrelevant and unknown',()=>{for(const k of ['unknown','non_screen'])assert(!C.matchesFilters({...fvideo,screenKind:k},{},defaults()));});
test('series included by default separate movie only',()=>{assert(C.matchesFilters({...fvideo,screenKind:'series'},{},defaults()));assert(!C.matchesFilters({...fvideo,screenKind:'series'},{},{...defaults(),content:'film'}));});
test('show all content allows manual review',()=>assert(C.matchesFilters({...fvideo,screenKind:'unknown'},{},{...defaults(),content:'all'})));
test('manual movie confirmation overrides weak metadata',()=>assert(C.matchesFilters({...fvideo,screenKind:'unknown'},{media:'screen'},defaults())));
test('manual nonfilm mark is separate from taste and origin',()=>{let s=C.apply(C.apply(C.blank(),v,'origin_foreign'),v,'like');s.records[v.id].memo='keep';s=C.apply(s,v,'media_no');const r=s.records[v.id];assert.equal(r.rating,'like');assert.equal(r.memo,'keep');assert.equal(r.origin,'non_korean');assert(!C.ready(v,r));assert(!C.needsReview(v,r));assert.throws(()=>C.apply(s,v,'candidate'));});
test('manual nonfilm reset restores eligibility without taste mutation',()=>{let s=C.apply(C.apply(C.blank(),v,'origin_foreign'),v,'media_no');s=C.apply(s,v,'media_reset');assert(C.ready(v,s.records[v.id]));assert.equal(s.records[v.id].rating,null);});
test('media confirmation does not confirm original country',()=>{const s=C.apply(C.blank(),v,'media_yes');assert.equal(s.records[v.id].origin,'unknown');assert(!C.ready(v,s.records[v.id]));});
test('v11 migrations preserve candidates notes',()=>{const r={schema:1,records:{[v.id]:{rating:'like',origin:'non_korean',stage:'candidate',memo:'keep'}}};const x=C.normalize(r).records[v.id];assert.equal(x.media,'unknown');assert.equal(x.stage,'candidate');assert.equal(x.memo,'keep');assert(C.ready(v,x));});
test('backup includes media no metadata',()=>{const data=C.exportData(C.apply(C.blank(),v,'media_no'));assert.equal(data.records[v.id].media,'not_screen');assert.equal(data.records[v.id].cache,undefined);});
test('filter preferences sanitize',()=>{const f=C.normalizeFilters({maxSubscribers:NaN,minSeconds:180,maxSeconds:10,languages:['xx','en','en','__proto__'],balance:'yes'});assert.equal(f.maxSubscribers,10000);assert.equal(f.minSeconds,0);assert.equal(f.maxSeconds,180);assert.deepEqual(f.languages,['en']);assert.equal(f.balance,true);});
test('funnel shows which restriction causes zero',()=>{const items=[fvideo,{...fvideo,id:'AbCdEfGhI02',subscribers:20000},{...fvideo,id:'AbCdEfGhI03',language:'hi'},{...fvideo,id:'AbCdEfGhI04',screenKind:'unknown'}];const n=C.filterCounts(items,{},defaults());assert.deepEqual(n,{total:4,content:3,subscribers:2,language:1,duration:1,views:1});});
test('language balancing interleaves, does not lose or duplicate',()=>{const items=[{id:'1',language:'en',channelId:'a'},{id:'2',language:'en',channelId:'a'},{id:'3',language:'en',channelId:'b'},{id:'4',language:'ja',channelId:'c'},{id:'5',language:'ja',channelId:'c'}];const result=C.balanceVideos(items,['en','ja']);assert.deepEqual(result.map(v=>v.id),['1','4','3','5','2']);assert.equal(new Set(result.map(v=>v.id)).size,items.length);});
test('language balancing handles empty, unknown, missing channel',()=>{assert.deepEqual(C.balanceVideos([]),[]);const items=[{id:'1'},{id:'2',language:'ar'}];assert.equal(C.balanceVideos(items).length,2);});
test('display filters do not mutate records',()=>{const s=C.apply(C.blank(),v,'like');const before=JSON.stringify(s);C.matchesFilters(fvideo,s.records[v.id],defaults());C.filterCounts([fvideo],s.records,defaults());assert.equal(JSON.stringify(s),before);});

test('movie-only does not turn confirmed TV into film',()=>{assert(!C.matchesFilters({...fvideo,screenKind:'series'},{origin:'non_korean'}, {...defaults(),content:'film'}));});
